// Generates public/sandbox/pyodide-worker.js from sandbox/pyodide.worker.template.js and the shared Python
// lockdown/prelude/epilogue in ../../sandbox (the same files the Node eval runner uses — parity by construction).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, "..");
const shared = join(web, "..", "..", "sandbox");
const version = JSON.parse(readFileSync(join(shared, "package.json"), "utf8")).dependencies.pyodide;
const py = (f) => JSON.stringify(readFileSync(join(shared, f), "utf8"));
const out = readFileSync(join(web, "sandbox", "pyodide.worker.template.js"), "utf8")
  .replace("__PYODIDE_VERSION__", version)
  .replace("__LOCKDOWN_PY__", py("lockdown.py"))
  .replace("__PRELUDE_PY__", py("prelude.py"))
  .replace("__EPILOGUE_PY__", py("epilogue.py"));
mkdirSync(join(web, "public", "sandbox"), { recursive: true });
writeFileSync(join(web, "public", "sandbox", "pyodide-worker.js"), out);
writeFileSync(join(web, "sandbox", "version.ts"), `// generated by scripts/sync-sandbox.mjs\nexport const PYODIDE_VERSION = "${version}";\n`);
console.log(`pyodide-worker.js generated (pyodide ${version})`);
